import { z } from "zod";

export const preJoiningSchema = z.object({
  fullName: z.string().min(1),
  dob: z.string().min(1),
  gender: z.string().min(1),
  bloodGroup: z.string().optional().default(""),
  mobile: z.string().min(1),
  altMobile: z.string().optional().default(""),
  email: z.string().email(),
  currentAddress: z.string().optional().default(""),
  permanentAddress: z.string().optional().default(""),
  emergencyName: z.string().optional().default(""),
  emergencyNumber: z.string().optional().default(""),
  position: z.string().min(1),
  department: z.string().min(1),
  joinDate: z.string().min(1),
  prevCompany: z.string().optional().default(""),
  experience: z.string().optional().default(""),
  skills: z.string().optional().default(""),
  linkedin: z.string().optional().default(""),
  portfolio: z.string().optional().default(""),
  bankName: z.string().min(1),
  accountHolder: z.string().optional().default(""),
  accountNumber: z.string().min(1),
  ifsc: z.string().min(1),
  branch: z.string().optional().default(""),
  signature: z.string().min(1),
  agree: z.literal(true),
  fileAadhaar: z.string().optional().default(""),
  filePan: z.string().optional().default(""),
  fileResume: z.string().optional().default(""),
  filePhoto: z.string().optional().default(""),
  fileEdu: z.string().optional().default(""),
  fileExp: z.string().optional().default(""),
});

export const postJoiningSchema = z.object({
  employeeId: z.string().min(1),
  officialEmail: z.string().email(),
  reportingManager: z.string().optional().default(""),
  workLocation: z.string().optional().default(""),
  employmentType: z.string().optional().default(""),
  shift: z.string().optional().default(""),
  joiningDate: z.string().min(1),
  uan: z.string().optional().default(""),
  pf: z.string().optional().default(""),
  esic: z.string().optional().default(""),
  salaryStructure: z.string().optional().default(""),
  ctc: z.string().optional().default(""),
  insurance: z.string().optional().default(""),
  laptop: z.string().optional().default(""),
  systemId: z.string().optional().default(""),
  idCard: z.boolean().default(false),
  emailAccess: z.boolean().default(false),
  softwareAccess: z.string().optional().default(""),
  nda: z.literal(true),
  companyPolicy: z.literal(true),
  leavePolicy: z.literal(true),
});

export const statusSchema = z.object({
  status: z.enum(["PENDING", "APPROVED", "JOINED", "REJECTED"]),
});
